# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: TestEnv
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Install redis-server
      run:
        sudo apt-get install -y redis-server redis-tools
    
    - name: Verify that redis is up
      run:
        redis-cli ping
      
    - name: Start redis
      run:
        redis-server --daemonize yes
    - name: Run tests
      env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          SERVER_ADDRESS: ${{ secrets.SERVER_ADDRESS }}
      run: npm test
    
    - name: Login to Docker
      uses: docker/login-action@v1
      with: 
        username: ${{ secrets.DOCKER_HUB_AHMET_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_AHMET_ACCESS_TOKEN }}
    
    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_AHMET_USERNAME }}/polkadot-explorer-server-actionhero:latest
